const WHATSAPP='905528538080';
const products=menuItems.flatMap(p=>p.cheese?[p,{...p,id:p.id+'-cheese',name:p.name+' + جبنة',price:p.price+p.cheese,image:p.cheeseImage||p.image,hidden:true,cheese:0}]:[p]);
const cart=new Map();let category='shawarma',toastTimer;const $=s=>document.querySelector(s);const money=n=>`${n.toLocaleString('en-US')} ₺`;const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderProducts(){const list=products.filter(p=>!p.hidden&&(category==='all'||p.category===category));$('#products').innerHTML=list.map(p=>`<article data-product="${p.id}" class="product ${p.image?'':'text-product'}">${p.image?`<div class="product-photo real-photo ${p.category==='drinks'?'drink-photo':p.category==='sauces'?'sauce-photo':''}"><img id="photo-${p.id}" src="${p.image}" alt="${p.name}" width="800" height="600" loading="lazy" decoding="async"></div>`:'<div class="product-photo photo-pending"><img src="brand-pin.jpg" alt="" width="48" height="64"><span>صورة الصنف قريبًا</span></div>'}<div class="product-body"><h3>${p.name}</h3>${p.turkish?`<span class="product-turkish" lang="tr" dir="ltr">${p.turkish}</span>`:''}<p>${p.description}</p>${p.imageNote?`<small class="serving-note">${p.imageNote}</small>`:''}${p.cheese?`<fieldset class="variant-options"><legend>اختيار الجبنة</legend><input type="hidden" id="variant-${p.id}" value="${p.id}"><label><input type="radio" name="cheese-${p.id}" data-variant="${p.id}" value="${p.id}" checked><span>بدون جبنة</span></label><label><input type="radio" name="cheese-${p.id}" data-variant="${p.id}" value="${p.id}-cheese"><span>مع جبنة <small>+${p.cheese} ₺</small></span></label></fieldset>`:''}<div class="product-bottom"><span class="price" id="price-${p.id}">${p.price} <small>₺</small></span><button class="add" data-add="${p.id}" aria-label="إضافة ${p.name} إلى السلة">＋ أضف للسلة</button></div></div></article>`).join('');document.querySelectorAll('#products [data-motion]').forEach((el,i)=>el.dataset.delay=String((i%3)*200));window.observeMotion?.($('#products'));}
document.addEventListener('change',e=>{if(e.target.matches('[data-variant]')){document.getElementById('variant-'+e.target.dataset.variant).value=e.target.value;const p=products.find(p=>p.id===e.target.value);$('#price-'+e.target.dataset.variant).textContent=money(p.price);const img=document.getElementById('photo-'+e.target.dataset.variant);if(img&&p.image){img.src=p.image;img.alt=p.name;}}});
function count(){return [...cart.values()].reduce((a,b)=>a+b,0)}function total(){return products.reduce((s,p)=>s+p.price*(cart.get(p.id)||0),0)}
function change(id,delta){if(!products.some(p=>p.id===id)||!Number.isInteger(delta))throw Error('Invalid product');const n=(cart.get(id)||0)+delta;if(n>99){notify('أقصى كمية للصنف 99');return false}if(n<=0)cart.delete(id);else cart.set(id,n);renderCart();if(delta>0)window.flameFeedback?.('اتضافت للسلة');return true;}
function notify(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2200)}
function renderCart(){window.syncCancel?.(count());document.querySelectorAll('.count').forEach(el=>el.textContent=count());$('#mobile-total').textContent=money(total());$('.mobile-cart').classList.toggle('visible',count()>0);$('#total').textContent=money(total());$('#checkout-area').hidden=count()===0;$('#cart-items').innerHTML=count()?products.filter(p=>cart.has(p.id)).map(p=>`<div class="cart-row">${p.image?`<img class="thumb real-thumb" src="${p.image}" alt="" width="68" height="68">`:''}<div><h3>${p.name}</h3><p>${money(p.price*cart.get(p.id))}</p></div><div class="qty"><button data-change="${p.id}" data-delta="-1" aria-label="تقليل كمية ${p.name}">−</button><span aria-label="الكمية">${cart.get(p.id)}</span><button data-change="${p.id}" data-delta="1" aria-label="زيادة كمية ${p.name}">+</button></div></div>`).join(''):'<div class="empty"><span>＋</span><h3>لسه مستنيين أول لقمة.</h3><p>ضيف وجبتك المفضلة وهنجهّز طلبك هنا.</p><button class="primary" id="back-menu">شوف المنيو</button></div>';}
let cartScroll=0,cartCloseTimer;
function closeCart(after){const dialog=$('#cart-dialog');if(!dialog.open||dialog.classList.contains('cart-closing'))return;const finish=()=>{clearTimeout(cartCloseTimer);dialog.classList.remove('cart-closing');dialog.close();after?.()};if(matchMedia('(prefers-reduced-motion: reduce)').matches){finish();return}dialog.classList.add('cart-closing');cartCloseTimer=setTimeout(finish,280);}
$('#cart-dialog').addEventListener('cancel',e=>{e.preventDefault();closeCart()});
function openCart(){renderCart();if($('#cart-dialog').open)return;cartScroll=scrollY;document.body.style.top=`-${cartScroll}px`;document.body.classList.add('cart-locked');$('#cart-dialog').showModal();}
$('#cart-dialog').addEventListener('close',()=>{document.body.classList.remove('cart-locked');document.body.style.top='';const root=document.documentElement,behavior=root.style.scrollBehavior;root.style.scrollBehavior='auto';window.scrollTo(0,cartScroll);root.style.scrollBehavior=behavior;});document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){if(change(document.getElementById('variant-'+add.dataset.add)?.value||add.dataset.add,1))notify('اتضافت للسلة · بالهنا!')}const qty=e.target.closest('[data-change]');if(qty)change(qty.dataset.change,Number(qty.dataset.delta));if(e.target.closest('[data-open-cart]'))openCart();if(e.target.closest('#close-cart'))closeCart();if(e.target.closest('#back-menu')){closeCart(()=>$('#menu').scrollIntoView({behavior:'smooth'}))}const filter=e.target.closest('[data-category]');if(filter&&filter.dataset.category!==category){category=filter.dataset.category;document.querySelectorAll('[data-category]').forEach(b=>{b.classList.toggle('selected',b===filter);b.setAttribute('aria-pressed',b===filter?'true':'false')});renderProducts();window.syncWheel?.(category);}});
$('#cart-dialog').addEventListener('click',e=>{if(e.target===$('#cart-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeCart()}});
function validMaps(value){try{const u=new URL(value);if(u.protocol!=='https:')return false;return u.hostname==='maps.app.goo.gl'&&u.pathname.length>1||u.hostname==='goo.gl'&&u.pathname.startsWith('/maps/')||(/^(www\.)?google\.(com|com\.tr|[a-z]{2}|co\.[a-z]{2})$/.test(u.hostname)&&u.pathname.startsWith('/maps'))||u.hostname==='maps.google.com';}catch{return false}}
$('#maps').addEventListener('input',()=>$('#maps').setCustomValidity(''));
$('#locate').addEventListener('click',()=>{const status=$('#location-status');if(!navigator.geolocation){status.textContent='المتصفح لا يدعم تحديد الموقع. الصق رابط Google Maps.';return}$('#locate').disabled=true;status.textContent='جاري تحديد موقعك…';navigator.geolocation.getCurrentPosition(p=>{$('#maps').value=`https://www.google.com/maps?q=${p.coords.latitude},${p.coords.longitude}`;$('#maps').setCustomValidity('');status.textContent='تم تحديد موقعك. تأكد إنه عنوان التوصيل وأضف تفاصيل المبنى.';$('#locate').disabled=false},()=>{status.textContent='تعذّر تحديد الموقع. اسمح بالوصول أو الصق رابط Google Maps يدويًا.';$('#locate').disabled=false},{enableHighAccuracy:true,timeout:12000,maximumAge:60000})});
function orderMessage(data){return ['مرحباً دونر ماب 👋','طلب جديد من الموقع — يرجى تأكيد التوفر والتوصيل.','',...products.filter(p=>cart.has(p.id)).map(p=>`${cart.get(p.id)} × ${p.name} — ${money(p.price*cart.get(p.id))}`),'',`مجموع الأصناف: ${money(total())}`,'رسوم التوصيل تُؤكد من المحل.',`الاسم: ${data.name}`,`الموقع: ${data.maps}`,`تفاصيل العنوان: ${data.address}`,data.notes?`ملاحظات: ${data.notes}`:''].filter(Boolean).join('\n')}
$('#checkout').addEventListener('submit',e=>{e.preventDefault();if(!count())return;const data=Object.fromEntries(new FormData(e.target));for(const key of Object.keys(data))data[key]=data[key].trim();for(const key of ['name','address']){const el=e.target.elements[key];el.setCustomValidity(data[key]?'':'اكتب هذا الحقل قبل المتابعة.');if(!data[key]){el.reportValidity();el.addEventListener('input',()=>el.setCustomValidity(''),{once:true});return}}if(!validMaps(data.maps)){$('#maps').setCustomValidity('الصق رابط موقع صالح من Google Maps يبدأ بـ https://');$('#maps').reportValidity();return}const href=`https://wa.me/${WHATSAPP}?text=${encodeURIComponent(orderMessage(data))}`;window.flameFeedback?.('طلبك جاهز لواتساب');window.open(href,'_blank','noopener,noreferrer');$('#submit-status').innerHTML=`الطلب جاهز، ولم يُرسل تلقائيًا. لو واتساب ما فتحش، <a href="${escapeHTML(href)}" target="_blank" rel="noopener noreferrer">افتح رسالة الطلب هنا</a>.`;});
function renderFavorites(){const ids=['bohca','rice-doner'];const descriptions={bohca:'شاورما، فطر وجبنة ذائبة في خبز لافاش.', 'rice-doner':'شاورما فوق الأرز، مع عيران ومخلل.', 'zinger-meal':'وجبة زنجر حار. لمحبي اللقمة الحارة.'};const root=$('#favorites');if(!root)return;root.innerHTML=ids.map((id,i)=>{const p=products.find(p=>p.id===id);return `<article class="favorite ${p.image?'':'favorite-spicy'}"><span class="favorite-label">${i===2?'لِمحبّي الحار':'الأكثر مبيعًا'}</span>${p.image?`<div class="favorite-image"><img src="${p.image}" alt="${p.name}" width="600" height="450" loading="lazy"></div>`:'<div class="spicy-type" aria-hidden="true">قرمشة.<br>ونار.</div>'}<div class="favorite-body"><h3>${p.name}</h3><p>${descriptions[id]}</p><div class="favorite-bottom"><strong>${money(p.price)}</strong><button class="add" data-add="${id}" aria-label="إضافة ${p.name} إلى السلة">＋ أضف للسلة</button></div></div></article>`}).join('')}
renderFavorites();renderProducts();renderCart();
if(document.modelContext?.registerTool){const life=new AbortController();const tools=[{name:'read_menu_and_cart',description:'Read the menu supplied by the restaurant customer and the current cart.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({products,cart:[...cart].map(([id,quantity])=>({id,quantity})),total:total(),demo:false})},{name:'add_to_cart',description:'Stage a menu item in the cart. Does not send an order.',inputSchema:{type:'object',properties:{productId:{type:'string'},quantity:{type:'integer',minimum:1,maximum:99}},required:['productId','quantity'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||!products.some(p=>p.id===input.productId)||!Number.isInteger(input.quantity)||input.quantity<1||input.quantity>99||(cart.get(input.productId)||0)+input.quantity>99)throw Error('Invalid product or quantity');change(input.productId,input.quantity);return {count:count(),total:total(),sent:false}}}];for(const tool of tools){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:life.signal})).catch(()=>{})}catch{}}window.addEventListener('pagehide',()=>life.abort(),{once:true})}

window.cancelDraft=()=>{cart.clear();$('#checkout').reset();$('#maps').setCustomValidity('');$('#customer-name').setCustomValidity('');$('#address').setCustomValidity('');$('#submit-status').textContent='';$('#location-status').textContent='';renderCart();notify('تم تفريغ السلة');};
